version: '3'

networks:
  iot:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8880:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - iot

  mysql:
    image: mysql:5.7.22
    container_name: mysql_iot
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "33077:3306"
    environment:
      MYSQL_DATABASE: iot
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - iot

  pma2:
      depends_on:
       - mysql
      image: phpmyadmin/phpmyadmin
      container_name: pma2
      restart: always
      ports:
       - '8890:80'
      environment:
        PMA_HOST: mysql
      networks:
      - iot
  
  # usage docker-compose run --rm php --version
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_iot
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - iot

  # usage docker-compose run --rm composer dump-autoload -o
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - iot
    
  # usage docker-compose run --rm artisan make:controller TestController
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - iot

  ###############################################################
  ################# Media Server Configuration ##################